"""create cart_item table

Revision ID: ea03c955fc22
Revises: 76a861cd6476
Create Date: 2025-06-02 17:41:13.390881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea03c955fc22'
down_revision = '76a861cd6476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
